databases:
  - name: entivation_DB
    databaseName: entivation_db
    user: entivation
    region: singapore

services:
  - type: web
    name: entivation
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: entivation_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false